definitions:
  error.ApiError:
    properties:
      causes:
        items:
          $ref: '#/definitions/error.Causes'
        type: array
      code:
        type: integer
      error:
        type: string
      message:
        type: string
    type: object
  error.Causes:
    properties:
      field:
        type: string
      message:
        type: string
    type: object
  secret.GenerateSecret.Request:
    properties:
      length:
        type: integer
      lowcase_characters:
        type: boolean
      numbers:
        type: boolean
      special_characters:
        type: boolean
      uppercase_characters:
        type: boolean
    type: object
info:
  contact: {}
paths:
  /file/converter:
    post:
      consumes:
      - multipart/form-data
      description: Convert a word file into pdf
      parameters:
      - description: File that will be converted
        in: formData
        name: file
        required: true
        type: file
      - description: Expected type that will be converted
        in: query
        name: expected_type
        required: true
        type: string
      produces:
      - multipart/form-data
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ApiError'
      summary: Document converter
      tags:
      - File
  /file/image/resizer:
    post:
      consumes:
      - multipart/form-data
      description: Edit an image based on the parameters in the request
      parameters:
      - description: JPEG image file to edit (only accepts .jpeg files)
        in: formData
        name: image
        required: true
        type: file
      - description: Image width
        in: query
        name: width
        type: integer
      - description: Image height
        in: query
        name: height
        type: integer
      produces:
      - image/jpeg
      responses:
        "200":
          description: Converted file
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ApiError'
      summary: Image Editor
      tags:
      - File
  /secret/generator:
    post:
      consumes:
      - application/json
      description: Generate secret based in the params
      parameters:
      - description: Lenght of the secret that'll be generated
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/secret.GenerateSecret.Request'
      produces:
      - application/json
      responses:
        "200":
          description: sl5=wv_X/OK/
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ApiError'
      summary: Secret Generator
      tags:
      - Secret
  /url/shortener:
    post:
      consumes:
      - application/json
      description: Shorten a URL using Bitly API
      parameters:
      - description: URL to shorten
        in: body
        name: url
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: https://bit.ly/example
          schema:
            type: string
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/error.ApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/error.ApiError'
      summary: URL Shortener
      tags:
      - URL
swagger: "2.0"
